### ISSUE TITLE
szene-streams addon not working on fire stick 2

### ISSUE THREAD

**Issue by firetv2user** [LaryLoose/laryloose.xbmc-addons#4]
Amazon Fire TV Stick 2 with Kodi 15.2 and FireStarter 3.2.2

Cannot access this addon (v 0.4.0). The log file recorded this error:

16:19:14 T:1803563712   ERROR: EXCEPTION: Unknown addon id 'plugin.video.szene-streams'.
16:19:14 T:1803563712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'plugin.video.szene-streams'.
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.szenestreams/default.py", line 10, in <module>
                                                settings = xbmcaddon.Addon(id='plugin.video.szene-streams')
                                            RuntimeError: Unknown addon id 'plugin.video.szene-streams'.
                                            -->End of Python script error report<--
16:19:14 T:1536729704   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.szenestreams/
16:19:14 T:1536729704   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.szenestreams/) failed
16:19:14 T:1772389640  NOTICE: Thread BackgroundLoader start, auto delete: false
16:19:14 T:1672953000 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer

---

It also doesn't work on my kodi 15.2 for windows 8 setup.

17:27:58 T:2408  NOTICE: Previous line repeats 1 times.
17:27:58 T:2408  NOTICE: Thread LanguageInvoker start, auto delete: false
17:27:58 T:2408  NOTICE: -->Python Interpreter Initialized<--
17:27:58 T:2408   ERROR: EXCEPTION: Unknown addon id 'plugin.video.szene-streams'.
17:27:58 T:2408   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'plugin.video.szene-streams'.
                                            Traceback (most recent call last):
                                              File "C:\Users***\AppData\Roaming\Kodi\addons\plugin.video.szenestreams\default.py", line 10, in <module>
                                                settings = xbmcaddon.Addon(id='plugin.video.szene-streams')
                                            RuntimeError: Unknown addon id 'plugin.video.szene-streams'.
                                            -->End of Python script error report<--
17:27:59 T:5268   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.szenestreams/
17:27:59 T:5268   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.szenestreams/) failed
17:27:59 T:7832  NOTICE: Thread BackgroundLoader start, auto delete: false

A fix is greatly appreciated! Thank you very much in advance!

**Comment by firetv2user** [comment]
Szene-streams works perfect on Kodi Helix 14.2.

Updating Kodi to Isengard or Jarvis Beta breaks the addon.
