### ISSUE TITLE
k1no addon not working on FireTVstick 2

### ISSUE THREAD

**Issue by firetv2user** [LaryLoose/laryloose.xbmc-addons#5]
Amazon FireTV stick 2 with Kodi 15.2 and FireStarter 3.2.2

Cannot access this addon (v 0.1.11). The log file recorded this error:

16:10:43 T:1659137264  NOTICE: Thread LanguageInvoker start, auto delete: false
16:10:43 T:1659137264  NOTICE: -->Python Interpreter Initialized<--
16:10:43 T:1659137264  NOTICE: http://k1no.do.am/load/?page1
16:10:43 T:1672953000 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
16:10:43 T:1659137264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 500: Server Error
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.k1no/default.py", line 167, in <module>
                                                if mode==None or url==None or len(url)<1: CATEGORIES(0)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.k1no/default.py", line 18, in CATEGORIES
                                                INDEX(baseurl+'/load/?page1')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.k1no/default.py", line 34, in INDEX
                                                data = getUrl(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.k1no/default.py", line 122, in getUrl
                                                response = urllib2.urlopen(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 126, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 397, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 510, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 435, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 369, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 518, in http_error_default
                                            HTTPError: HTTP Error 500: Server Error
                                            -->End of Python script error report<--
16:10:43 T:1536729704   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.k1no/
16:10:43 T:1536729704   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.k1no/) failed

---

It also does not work on my kodi 15.2 for windows 8 setup.

17:28:15 T:6392  NOTICE: Thread LanguageInvoker start, auto delete: false
17:28:15 T:6392  NOTICE: -->Python Interpreter Initialized<--
17:28:15 T:6392  NOTICE: http://k1no.do.am/load/?page1
17:28:16 T:6392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 500: Server Error
                                            Traceback (most recent call last):
                                              File "C:\Users***\AppData\Roaming\Kodi\addons\plugin.video.k1no\default.py", line 167, in <module>
                                                if mode==None or url==None or len(url)<1: CATEGORIES(0)
                                              File "C:\Users\**_\AppData\Roaming\Kodi\addons\plugin.video.k1no\default.py", line 18, in CATEGORIES
                                                INDEX(baseurl+'/load/?page1')
                                              File "C:\Users\_**\AppData\Roaming\Kodi\addons\plugin.video.k1no\default.py", line 34, in INDEX
                                                data = getUrl(url)
                                              File "C:\Users\**_\AppData\Roaming\Kodi\addons\plugin.video.k1no\default.py", line 122, in getUrl
                                                response = urllib2.urlopen(req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
                                                return self._call_chain(_args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 500: Server Error
                                            -->End of Python script error report<--
17:28:16 T:5268   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.k1no/
17:28:16 T:5268   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.k1no/) failed
17:28:16 T:9384  NOTICE: Thread BackgroundLoader start, auto delete: false

A fix is greatly appreciated! Thanks in advance!

**Comment by firetv2user** [comment]
K1no doesn't work on Kodi Helix 14.2, too (Amazon Fire TV Stick 2).
